name: Build, Lint, and Test

on:
  pull_request:
    branches: [main]

jobs:
  tox:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10.6", "3.12.3"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: pip install tox

      - name: Run tox
        run: |
          version=${{ matrix.python-version }}
          version_nodot=${version//./}
          tox -e py${version_nodot},lint
